name: Lint

on:
  push:
    branches: [ develop, staging ]
  pull_request:
    branches: [ develop, staging ]

permissions: read-all

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get shared php setup
        uses: ./.github/actions/php
        with:
          php-version: '8.2'

      - name: Lint twig templates
        run: ./bin/console lint:twig templates --env=prod

      - name: Lint yaml config
        run: ./bin/console lint:yaml config --parse-tags

      - name: Validate doctrine schema
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
