name: Security Checks

on:
  push:
    branches: [ develop, staging, main ]
  pull_request:
    branches: [ develop, staging, main ]

permissions: read-all

jobs:
  SecurityChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get shared php setup
        uses: ./.github/actions/php
        with:
          php-version: '8.2'

      - name: Run Symfony Security Check
        run: $HOME/bin/symfony check:security

      - name: Check for outdated Composer dependencies
        run: composer outdated --direct --strict
